// <auto-generated />
using System;
using MehmetHusnaKisla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MehmetHusnaKisla.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MehmetHusnaKisla.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ADMIN_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"), 2L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PasswordConfirm")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("PASSWORD_CONFIRM");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("AdminID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ADMINS", (string)null);

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            Password = "123",
                            PasswordConfirm = "123",
                            UserName = "mhusna"
                        });
                });

            modelBuilder.Entity("MehmetHusnaKisla.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ALBUM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumID"), 1L, 1);

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ALBUM_NAME");

                    b.Property<int?>("ArtistID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ARTIST_ID");

                    b.Property<double>("Discount")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("DISCOUNT");

                    b.Property<DateTime>("InsertTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("INSERT_TIME");

                    b.Property<int>("IsOnSale")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IS_ON_SALE");

                    b.Property<double>("Price")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PRICE");

                    b.Property<DateTime>("PublishTime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PUBLISH_TIME");

                    b.HasKey("AlbumID");

                    b.HasIndex("ArtistID");

                    b.ToTable("ALBUMS", (string)null);
                });

            modelBuilder.Entity("MehmetHusnaKisla.Models.Artist", b =>
                {
                    b.Property<int>("ArtistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ARTIST_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistID"), 1L, 1);

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ARTIST_NAME");

                    b.Property<int>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(1)
                        .HasColumnName("IS_DELETED");

                    b.HasKey("ArtistID");

                    b.ToTable("ARTISTS", (string)null);
                });

            modelBuilder.Entity("MehmetHusnaKisla.Models.Album", b =>
                {
                    b.HasOne("MehmetHusnaKisla.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistID");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MehmetHusnaKisla.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
