// <auto-generated />
using System;
using BookShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BookShop.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231111092009_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookShop.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ADMIN_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"), 2L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ADMIN_AD");

                    b.Property<string>("MailAdresi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MAIL_ADRESI");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("SIFRE");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ADMIN_SOYAD");

                    b.HasKey("AdminID");

                    b.ToTable("ADMINLER", (string)null);

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            Ad = "Mehmet",
                            MailAdresi = "admin@gmail.com",
                            Sifre = "admin",
                            Soyad = "Kisla"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Kitap", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("KITAP_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapID"), 1L, 1);

                    b.Property<double>("Fiyat")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("FIYAT");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR2(40)")
                        .HasColumnName("KITAP_ADI");

                    b.Property<int>("SatisDurum")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SATIS_DURUM");

                    b.Property<int?>("YayinEviID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YAYINEVI_ID");

                    b.HasKey("KitapID");

                    b.HasIndex("YayinEviID");

                    b.ToTable("KITAPLAR", (string)null);
                });

            modelBuilder.Entity("BookShop.Models.YayinEvi", b =>
                {
                    b.Property<int>("YayinEviID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("YAYINEVI_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YayinEviID"), 3L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("YAYINEVI_ADI");

                    b.HasKey("YayinEviID");

                    b.ToTable("YAYINEVLERI", (string)null);

                    b.HasData(
                        new
                        {
                            YayinEviID = 1,
                            Ad = "Kültür Yayınevi"
                        },
                        new
                        {
                            YayinEviID = 2,
                            Ad = "Zambak Yayınevi"
                        });
                });

            modelBuilder.Entity("BookShop.Models.Kitap", b =>
                {
                    b.HasOne("BookShop.Models.YayinEvi", "YayinEvi")
                        .WithMany("Kitaplar")
                        .HasForeignKey("YayinEviID");

                    b.Navigation("YayinEvi");
                });

            modelBuilder.Entity("BookShop.Models.YayinEvi", b =>
                {
                    b.Navigation("Kitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
