// <auto-generated />
using System;
using EntityFramework_III.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EntityFramework_III.Migrations
{
    [DbContext(typeof(OkulContext))]
    [Migration("20231103132730_InitWithValues")]
    partial class InitWithValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityFramework_III.Models.Ders", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersID"), 1L, 1);

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Kredi")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("DersID");

                    b.ToTable("DERSLER");

                    b.HasData(
                        new
                        {
                            DersID = 10,
                            DersAdi = "Mat 101",
                            Kredi = 6
                        },
                        new
                        {
                            DersID = 11,
                            DersAdi = "Mat 102",
                            Kredi = 4
                        },
                        new
                        {
                            DersID = 12,
                            DersAdi = "Fizik 101",
                            Kredi = 3
                        },
                        new
                        {
                            DersID = 13,
                            DersAdi = "Polifoni",
                            Kredi = 2
                        },
                        new
                        {
                            DersID = 14,
                            DersAdi = "Kimya",
                            Kredi = 2
                        });
                });

            modelBuilder.Entity("EntityFramework_III.Models.Egitmen", b =>
                {
                    b.Property<int>("EgitmenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EgitmenID");

                    b.ToTable("EGITMENLER");

                    b.HasData(
                        new
                        {
                            EgitmenID = 20,
                            Ad = "Cevat",
                            Soyad = "Külyutmaz"
                        },
                        new
                        {
                            EgitmenID = 21,
                            Ad = "Cavit",
                            Soyad = "Sifirci"
                        });
                });

            modelBuilder.Entity("EntityFramework_III.Models.EgitmenDers", b =>
                {
                    b.Property<int>("EgitmenDersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenDersID"), 1L, 1);

                    b.Property<int>("DersID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EgitmenID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("EgitmenDersID");

                    b.HasIndex("DersID");

                    b.HasIndex("EgitmenID");

                    b.ToTable("EGITMENDERS");

                    b.HasData(
                        new
                        {
                            EgitmenDersID = 1,
                            DersID = 10,
                            EgitmenID = 20
                        },
                        new
                        {
                            EgitmenDersID = 2,
                            DersID = 11,
                            EgitmenID = 20
                        },
                        new
                        {
                            EgitmenDersID = 3,
                            DersID = 12,
                            EgitmenID = 20
                        },
                        new
                        {
                            EgitmenDersID = 4,
                            DersID = 13,
                            EgitmenID = 21
                        },
                        new
                        {
                            EgitmenDersID = 5,
                            DersID = 14,
                            EgitmenID = 21
                        });
                });

            modelBuilder.Entity("EntityFramework_III.Models.HarfNot", b =>
                {
                    b.Property<int>("HarfNotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HarfNotID"), 1L, 1);

                    b.Property<string>("Harf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("MaxDeger")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MinDeger")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("HarfNotID");

                    b.ToTable("HARFNOTLARI");
                });

            modelBuilder.Entity("EntityFramework_III.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("OgrenciID");

                    b.ToTable("OGRENCILER");

                    b.HasData(
                        new
                        {
                            OgrenciID = 1,
                            Ad = "Cevdet",
                            Soyad = "Durmaz"
                        },
                        new
                        {
                            OgrenciID = 2,
                            Ad = "Selami",
                            Soyad = "Dursun"
                        },
                        new
                        {
                            OgrenciID = 3,
                            Ad = "Dursun",
                            Soyad = "Durmasın"
                        });
                });

            modelBuilder.Entity("EntityFramework_III.Models.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciDersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciDersID"), 1L, 1);

                    b.Property<int>("DersID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("HarfNotID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Not")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("OgrenciDersID");

                    b.HasIndex("DersID");

                    b.HasIndex("HarfNotID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("OGRENCIDERS");

                    b.HasData(
                        new
                        {
                            OgrenciDersID = 1,
                            DersID = 10,
                            Not = 78,
                            OgrenciID = 1
                        },
                        new
                        {
                            OgrenciDersID = 2,
                            DersID = 13,
                            Not = 55,
                            OgrenciID = 1
                        },
                        new
                        {
                            OgrenciDersID = 3,
                            DersID = 14,
                            Not = 66,
                            OgrenciID = 1
                        },
                        new
                        {
                            OgrenciDersID = 4,
                            DersID = 10,
                            Not = 66,
                            OgrenciID = 2
                        },
                        new
                        {
                            OgrenciDersID = 5,
                            DersID = 11,
                            Not = 50,
                            OgrenciID = 3
                        });
                });

            modelBuilder.Entity("EntityFramework_III.Models.EgitmenDers", b =>
                {
                    b.HasOne("EntityFramework_III.Models.Ders", "Ders")
                        .WithMany("Egitmenler")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_III.Models.Egitmen", "Egitmen")
                        .WithMany("Dersler")
                        .HasForeignKey("EgitmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("EntityFramework_III.Models.OgrenciDers", b =>
                {
                    b.HasOne("EntityFramework_III.Models.Ders", "Ders")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_III.Models.HarfNot", "HarfNot")
                        .WithMany("Dersler")
                        .HasForeignKey("HarfNotID");

                    b.HasOne("EntityFramework_III.Models.Ogrenci", "Ogrenci")
                        .WithMany("Dersler")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("HarfNot");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("EntityFramework_III.Models.Ders", b =>
                {
                    b.Navigation("Egitmenler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("EntityFramework_III.Models.Egitmen", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("EntityFramework_III.Models.HarfNot", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("EntityFramework_III.Models.Ogrenci", b =>
                {
                    b.Navigation("Dersler");
                });
#pragma warning restore 612, 618
        }
    }
}
