// <auto-generated />
using System;
using EntityFramework_I_Tekrar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EntityFramework_I_Tekrar.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.Bolum", b =>
                {
                    b.Property<int>("BolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumID"), 1L, 1);

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("BolumID");

                    b.ToTable("BOLUMLER");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelID"), 1L, 1);

                    b.Property<int>("BolumID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Maas")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("PersonelAd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("PersonelID");

                    b.HasIndex("BolumID");

                    b.ToTable("PERSONELLER");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.PersonelDetay", b =>
                {
                    b.Property<int>("PersonelDetayID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SicilNotu")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PersonelDetayID");

                    b.ToTable("PERSONELDETAYLAR");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.PersonelProje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BolumID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PersonelID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProjeID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID");

                    b.HasIndex("BolumID");

                    b.HasIndex("PersonelID");

                    b.HasIndex("ProjeID");

                    b.ToTable("PERSONELPROJELERI");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.Proje", b =>
                {
                    b.Property<int>("ProjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjeID"), 1L, 1);

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ProjeID");

                    b.ToTable("PROJELER");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.Personel", b =>
                {
                    b.HasOne("EntityFramework_I_Tekrar.Models.Bolum", "Bolum")
                        .WithMany("Personeller")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.PersonelDetay", b =>
                {
                    b.HasOne("EntityFramework_I_Tekrar.Models.Personel", "Personel")
                        .WithOne("PersonelDetay")
                        .HasForeignKey("EntityFramework_I_Tekrar.Models.PersonelDetay", "PersonelDetayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.PersonelProje", b =>
                {
                    b.HasOne("EntityFramework_I_Tekrar.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_I_Tekrar.Models.Personel", "Personel")
                        .WithMany("Projeler")
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_I_Tekrar.Models.Proje", null)
                        .WithMany("Personeller")
                        .HasForeignKey("ProjeID");

                    b.Navigation("Bolum");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.Bolum", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.Personel", b =>
                {
                    b.Navigation("PersonelDetay")
                        .IsRequired();

                    b.Navigation("Projeler");
                });

            modelBuilder.Entity("EntityFramework_I_Tekrar.Models.Proje", b =>
                {
                    b.Navigation("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
