// <auto-generated />
using EntityFramework_II.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EntityFramework_II.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityFramework_II.Models.Ders", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersID"), 1L, 1);

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("DersID");

                    b.ToTable("DERSLER");
                });

            modelBuilder.Entity("EntityFramework_II.Models.DersEgitmen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DersID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("EgitmenID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID");

                    b.HasIndex("DersID");

                    b.HasIndex("EgitmenID");

                    b.ToTable("DERSEGITMENLER");
                });

            modelBuilder.Entity("EntityFramework_II.Models.DersOgrenci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DersID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("DersNotu")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("HarfNotu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID");

                    b.HasIndex("DersID");

                    b.HasIndex("OgrenciID");

                    b.ToTable("DERSOGRENCILER");
                });

            modelBuilder.Entity("EntityFramework_II.Models.Egitmen", b =>
                {
                    b.Property<int>("EgitmenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EgitmenID");

                    b.ToTable("EGITMENLER");
                });

            modelBuilder.Entity("EntityFramework_II.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("OgrenciID");

                    b.ToTable("OGRENCILER");
                });

            modelBuilder.Entity("EntityFramework_II.Models.DersEgitmen", b =>
                {
                    b.HasOne("EntityFramework_II.Models.Ders", "Ders")
                        .WithMany("Egitmenler")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_II.Models.Egitmen", "Egitmen")
                        .WithMany("Dersler")
                        .HasForeignKey("EgitmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("EntityFramework_II.Models.DersOgrenci", b =>
                {
                    b.HasOne("EntityFramework_II.Models.Ders", "Ders")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFramework_II.Models.Ogrenci", "Ogrenci")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("OgrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("EntityFramework_II.Models.Ders", b =>
                {
                    b.Navigation("Egitmenler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("EntityFramework_II.Models.Egitmen", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("EntityFramework_II.Models.Ogrenci", b =>
                {
                    b.Navigation("Ogrenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
